config/routes.rb
Rails.application.routes.draw do
  get 'profile/show'

  get 'profile/edit'

  get 'social/index'
  get 'social/show_profile'
  patch 'social/update'

  get 'accounts/facebook'
  get 'accounts/instagram'
  get 'accounts/twitter'
  get 'accounts/google_oauth2'

  get 'auth/facebook/callback', to: 'accounts#facebook'
  get 'auth/twitter/callback', to: 'accounts#twitter'
  get 'auth/google_oauth2/callback', to: 'accounts#google_oauth2'
  get 'auth/instagram/callback', to: 'accounts#instagram'
  
  get 'auth/failure', to: redirect('/')

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:edit, :update]
  root 'social#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  def self.auth_instagram(auth, current_user)
    current_user.accounts.create( provider: auth.provider, uid: auth.uid,
                                  oauth_token: auth.credentials.token,
                                  user_name: auth.info.name,
                                  user_email: auth.info.email,
                                  user_avatar: auth.info.image)
  end

  def self.auth_facebook(auth, current_user)
    current_user.accounts.create( provider: auth.provider, uid: auth.uid,
                                  oauth_token: auth.credentials.token,
                                  user_name: auth.info.name,
                                  user_email: auth.info.email,
                                  user_avatar: auth.info.image)
  end

  def self.auth_google_oauth2(auth, current_user)
    current_user.accounts.create( provider: auth.provider, uid: auth.uid,
                                  oauth_token: auth.credentials.token,
                                  user_name: auth.info.name,
                                  user_email: auth.info.email,
                                  user_avatar: auth.info.image,
                                  user_gender: auth.extra.raw_info.gender)
  end

  def self.auth_twitter(auth, current_user)
    current_user.accounts.create( provider: auth.provider, uid: auth.uid,
                                  oauth_token: auth.credentials.token,
                                  user_name: auth.info.name,
                                  user_email: auth.info.email,
                                  user_avatar: auth.info.image,
                                  user_address: auth.extra.raw_info.location)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  has_many :accounts
  mount_uploader :user_avatar, FileUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.user_name = auth.info.name
      user.remote_user_avatar_url = auth.info.image
    end
  end

  def self.get_data(auth, current_user)
    current_user.accounts.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.user_email = auth.info.email
      user.user_name = auth.info.name
      user.user_avatar = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :config_permitted_params, if: :devise_controller?

  protected
  def config_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name, :gender, :birthday, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name, :gender, :birthday, :address])
  end
end

app/controllers/social_controller.rb
class SocialController < ApplicationController
  before_action :authenticate_user!
  def index
    @accounts = Account.all
    @account = current_user.accounts.find_by_provider(params[:provider])
  end
  def show_profile
    
  end
  def update
    current_user.update(
      remote_user_avatar_url: params[:avatar], user_name: params[:name],
      user_gender: params[:gender], user_birthday: params[:birthday],
      user_address: params[:address]
      )
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def all
    if current_user
      @account = User.get_data(request.env["omniauth.auth"], current_user)
      redirect_to root_path
    else
      @account = Account.find_by_uid(request.env["omniauth.auth"].uid)
      if @account.present?
        @user = @account.user
        sign_in_and_redirect @user, :event => :authentication
      else
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
          User.get_data(request.env["omniauth.auth"], @user)
          sign_in_and_redirect @user, :event => :authentication
        else
          session["devise.user_attributes"] = request.env["omniauth.auth"]
          redirect_to root_path
        end
      end
    end
  end

  def failure
    redirect_to root_path
  end

  alias_method :facebook, :all
  alias_method :twitter, :all
  alias_method :google_oauth2, :all
  alias_method :instagram, :all

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:user_avatar, :user_name, :user_gender,
                                 :user_birthday, :user_address, :user_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/social_helper.rb
module SocialHelper
  def user_avatar
    if @account
      if @account.user_avatar
        @account.user_avatar
      else
        "NO DATA"
      end
    end
  end

  def user_address
    if @account
      if @account.user_address
        @account.user_address
      else
        "NO DATA"
      end
    end
  end

  def user_birthday
    if @account
      if @account.user_birthday
        @account.user_birthday
      else
        "NO DATA"
      end
    end
  end

  def user_gender
    if @account
      if @account.user_gender
        @account.user_gender
      else
        "NO DATA"
      end
    end
  end

  def user_name
    if @account
      if @account.user_name
        @account.user_name
      else
        "NO DATA"
      end
    end
  end

  def account_signed_in(account)
    if current_user.provider
      current_user.provider.downcase != account.downcase
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialhub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
      <div class="container">
        <%= yield %>
      </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="container navigation-bar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href=<%= root_path %> >SOCIAL-HUB</a>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a data-no-turbolink="true" rel="nofollow" data-method="delete" href= <%= destroy_user_session_path %> >Sign out</a></li>
        <li><a href=<%= edit_user_registration_path %> >Settings</a></li>
      <% else %>
        <li><a href=<%= new_user_session_path %> >Sign in</a></li>
        <li><a href=<%= new_user_registration_path %> >Sign up</a></li>
      <% end %>
    </ul>
  </div><!--/.nav-collapse -->
</div>

app/views/social/_filtered_account.html.erb
<ul>
<% if current_user.provider.downcase != "facebook" %>
  <li class="facebook-connect">
    <i class="fa fa-facebook fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Facebook</h4>".html_safe, user_facebook_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "facebook"), remote: true %></span>
  </li>
<% end %>
<% if current_user.provider.downcase != "twitter" %>
  <li class="twitter-connect">
    <i class="fa fa-twitter fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Twitter</h4>".html_safe, user_twitter_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "twitter"), remote: true %></span>
  </li>
<% end %>
<% if current_user.provider.downcase != "google_oauth2" %>
  <li class="googleplus-connect">
    <i class="fa fa-google-plus fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Google plus</h4>".html_safe, user_google_oauth2_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "google_oauth2"), remote: true %></span>
  </li>
<% end %>
<% if current_user.provider.downcase != "instagram" %>
  <li class="instagram-connect">
    <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Instagram</h4>".html_safe, user_instagram_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "instagram"), remote: true %></span>
  </li>
<% end %>
</ul>

app/views/social/_full_account.html.erb
<ul>
  <li class="facebook-connect">
    <i class="fa fa-facebook fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Facebook</h4>".html_safe, user_facebook_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "facebook"), remote: true %></span>
  </li>
  <li class="twitter-connect">
    <i class="fa fa-twitter fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Twitter</h4>".html_safe, user_twitter_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "twitter"), remote: true %></span>
  </li>
  <li class="googleplus-connect">
    <i class="fa fa-google-plus fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Google plus</h4>".html_safe, user_google_oauth2_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "google_oauth2"), remote: true %></span>
  </li>
  <li class="instagram-connect">
    <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
    <span class="account"><%= link_to "<h4>Instagram</h4>".html_safe, user_instagram_omniauth_authorize_path %></span>
    <span class="other_account"><%= link_to "<p>show profile</p>".html_safe, social_index_path(:provider => "instagram"), remote: true %></span>
  </li>
</ul>

app/views/social/_main_profile.html.erb
<div class="row">
  <div class="col-sm-4 avatar">
    <img src= <%= current_user.user_avatar %> class="img-responsive" >
  </div>
  <div class="col-sm-8">
    <div id="user_name">
      <h4>User name: <%= current_user.user_name %></h4>
      <br/>
    </div>

    <div id="user_email">
      <h4>Email: <%= current_user.email %></h4>
      <br/>
    </div>

    <div id="user_gender">
      <h4>Gender: <%= current_user.user_gender %></h4>
      <br/>
    </div>

    <div id="user_birthday">
      <h4>Birth day: <%= current_user.user_birthday %></h4>
      <br/>
    </div>
    <div id="user_address">
      <h4>Address: <%= current_user.user_address %></h4>
      <br/>
    </div>
  </div>
</div>
<div class="row">
  <%= link_to "Edit profile", edit_user_path(current_user.id), remote: true, class: "btn btn-primary pull-right" %>
</div>

app/views/social/_profile.html.erb
<div class="row">
  <div class="col-sm-4 avatar">
    <img src= <%= user_avatar %> class="img-responsive">
  </div>
  <div class="col-sm-8">
    <div id="user_name">
      <h4>User name: <%= user_name %></h4>
      <br/>
    </div>
    <div id="user_gender">
      <h4>Gender: <%= user_gender %></h4>
      <br/>
    </div>

    <div id="user_birthday">
      <h4>Birth day: <%= user_birthday %></h4>
      <br/>
    </div>
    <div id="user_address">
      <h4>Address: <%= user_address %></h4>
      <br/>
    </div>
  </div>
</div>
<div class="row">
  <%= link_to "Sync data to my account", social_update_path(avatar: user_avatar,name: user_name, gender: user_gender, birthday: user_birthday, address: user_address), method: :patch , class: "btn btn-primary pull-right" %>
</div>

app/views/social/index.html.erb
<div class="row">
  <div class="col-sm-3" id="left-side">
    <div class="row">
        <%= render "full_account" %>
    </div>

    <div class="row" id="myprofile">
      <%= link_to "My profile", social_show_profile_path(:provider => "main"), remote: true, class: "btn btn-primary pull-right" %>
    </div>
  </div>

  <div class="col-sm-9" id="right-side">
    <div class="row" id="profile">
      <% if flash[:notice] %>
        <div class="alert alert-warning"><%= flash[:notice] %></div>
      <% end %>
      <%= render "main_profile" %>
    </div>
  </div>
</div>

app/views/social/index.js.erb
$("#profile").html("<%= j render(:partial => 'profile') %>");

app/views/social/show_profile.js.erb
$("#profile").html("<%= j render(:partial => 'main_profile') %>");

app/views/users/_edit_user.html.erb
<div class="col-sm-12">
  <div class="panel panel-default devise-bs">
    <div class="panel-heading">
      <h4>Update profile</h4>
    </div>
    <div class="panel-body">
      <%= form_for(@user) do |f| %>
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :user_avatar %>
          <img src= <%= current_user.user_avatar %> class="img-responsive" width=90 height=90 >
          <%= f.file_field :user_avatar %>
        </div>
        <div class="form-group">
          <%= f.label :user_gender %>
          <%= f.select :user_gender, options_for_select(["Male", "Female"]), class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :user_birthday %>
          <%= f.date_select :user_birthday, start_year: 1900, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :user_address %>
          <%= f.text_field :user_address, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.hidden_field :email, value: current_user.email, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.js.erb
$("#profile").html("<%= j render(:partial => 'edit_user') %>");